baseURL = "/"
languageCode = "en-us"
title = "ioBUILDERS"
theme = "atomic"
copyright = "&copy; 2018 ioBUILDERS -- All rights reserved."
[author]
  #name = "ioBUILDERS"
  #github = "https://github.com/ddaniel-gomez"
  #email = "ddaniel.gomez@gmail.com"
[params]
    description = "Take the challenge"
    author_url = "https://www.sadmedia.com"
    #google_analytics = "UA-xxxx"
    #project_url = ""
    #project_documentation = ""
    #github_project_name = ""
    #github_user_name = ""

    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"
